/**
 * Generate `lib/brand-icons.generated.ts` from `lib/brand-slugs.ts`.
 *
 *   npm run build:brand-icons
 *
 * Emits only the slugs the two catalogs actually reference — the full Simple
 * Icons set is ~3,450 marks and has no business in a page bundle. Fails on a
 * slug that does not exist, so a typo in the curation is a build error rather
 * than a mark that silently degrades to a monogram.
 *
 * `simple-icons` is a devDependency: it is read here, at build time, and never
 * imported by the app. What ships is this script's committed output.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import * as simpleIcons from "simple-icons";

import { CLI_BRAND_SLUGS, MCP_BRAND_SLUGS, referencedSlugs } from "../lib/brand-slugs";

type Icon = { title: string; slug: string; hex: string; path: string };

const bySlug = new Map<string, Icon>();
for (const value of Object.values(simpleIcons as Record<string, unknown>)) {
  const icon = value as Icon | undefined;
  if (icon?.slug && icon.path) bySlug.set(icon.slug, icon);
}

const wanted = referencedSlugs();
const missing = wanted.filter((slug) => !bySlug.has(slug));
if (missing.length > 0) {
  console.error(
    `build-brand-icons: ${missing.length} slug(s) are not in simple-icons — fix lib/brand-slugs.ts:\n` +
      missing.map((slug) => `  - ${slug}`).join("\n"),
  );
  process.exit(1);
}

const entries = wanted.map((slug) => {
  const icon = bySlug.get(slug)!;
  return { slug, title: icon.title, hex: icon.hex, path: icon.path };
});

const literal = (value: string) => JSON.stringify(value);
const record = (rows: Readonly<Record<string, string>>) =>
  Object.entries(rows)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, slug]) => `  ${literal(id)}: ${literal(slug)},`)
    .join("\n");

const output = `/**
 * GENERATED by scripts/build-brand-icons.mts — do not edit.
 *
 * Run \`npm run build:brand-icons\` after changing lib/brand-slugs.ts.
 *
 * Icon paths come from the \`simple-icons\` package, which is CC0. The brands
 * themselves are trademarks of their owners; the marks identify a product and
 * imply no endorsement.
 */

/** One brand mark: a 24×24 path, plus the brand's own colour if ever wanted. */
export interface BrandIcon {
  /** The brand's proper name, for \`aria-label\` / \`title\`. */
  title: string;
  /** Brand hex without the leading \`#\`. Unused by default — see BrandIcon.tsx. */
  hex: string;
  /** Single \`d\` attribute for a 0 0 24 24 viewBox. */
  path: string;
}

export const BRAND_ICONS: Readonly<Record<string, BrandIcon>> = {
${entries
  .map(
    (icon) =>
      `  ${literal(icon.slug)}: {\n    title: ${literal(icon.title)},\n    hex: ${literal(icon.hex)},\n    path: ${literal(icon.path)},\n  },`,
  )
  .join("\n")}
};

/** MCP catalog entry id → slug. */
export const MCP_ICON_SLUGS: Readonly<Record<string, string>> = {
${record(MCP_BRAND_SLUGS)}
};

/** CLI app id → slug. */
export const CLI_ICON_SLUGS: Readonly<Record<string, string>> = {
${record(CLI_BRAND_SLUGS)}
};
`;

const target = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "lib",
  "brand-icons.generated.ts",
);
writeFileSync(target, output, "utf8");
console.log(
  `build-brand-icons: ${entries.length} marks → ${path.relative(process.cwd(), target)} ` +
    `(${(output.length / 1024).toFixed(1)} KB)`,
);
