"""Apache Tika 4 input-format routing hints.

Tika content-sniffs more than a thousand types and a server may load custom
parsers, so this set is deliberately a routing/upload hint rather than a hard
allow-list. :class:`TikaParser` delegates final support decisions to the remote
server and therefore advertises an unbounded set to ParseService.
"""

from __future__ import annotations

import re

from .._versions import version_at_least

MIN_TIKA_VERSION = "4.0.0"

# Common filename extensions for the standard Tika 4 parser distribution.
# MIME types with no conventional suffix remain usable through direct/CLI
# ingestion because the Tika adapter itself does not pre-filter extensions.
TIKA_4_0_0_KNOWN_FORMATS = frozenset(
    {
        # Documents, publishing, Office, OpenDocument and iWork
        ".pdf",
        ".epub",
        ".ibooks",
        ".fb2",
        ".rtf",
        ".doc",
        ".docx",
        ".docm",
        ".dot",
        ".dotx",
        ".dotm",
        ".xls",
        ".xlsx",
        ".xlsm",
        ".xlsb",
        ".xlt",
        ".xltx",
        ".xltm",
        ".ppt",
        ".pptx",
        ".pptm",
        ".pot",
        ".potx",
        ".potm",
        ".pps",
        ".ppsx",
        ".ppsm",
        ".sldx",
        ".sldm",
        ".ppam",
        ".vsd",
        ".vsdx",
        ".vsdm",
        ".vssx",
        ".vssm",
        ".vstx",
        ".vstm",
        ".mpp",
        ".pub",
        ".one",
        ".xps",
        ".dwfx",
        ".odt",
        ".ott",
        ".odm",
        ".oth",
        ".ods",
        ".ots",
        ".odp",
        ".otp",
        ".odg",
        ".otg",
        ".odf",
        ".fodt",
        ".fods",
        ".fodp",
        ".pages",
        ".numbers",
        ".key",
        ".wpd",
        ".qpw",
        ".idml",
        ".mif",
        ".hwp",
        ".hwpx",
        # Web, feeds, mail and plain/structured text
        ".html",
        ".htm",
        ".xhtml",
        ".xml",
        ".txt",
        ".text",
        ".md",
        ".markdown",
        ".csv",
        ".tsv",
        ".rss",
        ".atom",
        ".eml",
        ".msg",
        ".pst",
        ".mbox",
        ".tnef",
        ".chm",
        ".warc",
        ".wacz",
        ".tmx",
        ".xlf",
        ".xliff",
        # Archives and packages
        ".zip",
        ".tar",
        ".tar.gz",
        ".tgz",
        ".gz",
        ".bz",
        ".bz2",
        ".xz",
        ".lzma",
        ".z",
        ".7z",
        ".rar",
        ".ar",
        ".arj",
        ".cpio",
        ".jar",
        ".war",
        ".ear",
        # Images, drawings and design files
        ".bmp",
        ".gif",
        ".heic",
        ".heif",
        ".icns",
        ".ico",
        ".jbig2",
        ".jpeg",
        ".jpg",
        ".jxl",
        ".png",
        ".psd",
        ".tif",
        ".tiff",
        ".webp",
        ".wmf",
        ".emf",
        ".xcf",
        ".bpg",
        # Audio and video
        ".aif",
        ".aiff",
        ".au",
        ".mid",
        ".midi",
        ".wav",
        ".mp3",
        ".m4a",
        ".flac",
        ".ogg",
        ".oga",
        ".opus",
        ".spx",
        ".mp4",
        ".m4v",
        ".mov",
        ".3gp",
        ".3g2",
        ".flv",
        ".ogv",
        ".avi",
        ".mpeg",
        ".mpg",
        ".mkv",
        ".webm",
        # CAD, science, database, fonts, crypto and executables
        ".dwg",
        ".dgn",
        ".dbf",
        ".dif",
        ".mat",
        ".nc",
        ".hdf",
        ".h5",
        ".grb",
        ".grib",
        ".sqlite",
        ".sqlite3",
        ".mdb",
        ".accdb",
        ".sas7bdat",
        ".ttf",
        ".otf",
        ".afm",
        ".p7s",
        ".p7m",
        ".p12",
        ".pfx",
        ".tsd",
        ".class",
        ".exe",
        ".dll",
        ".so",
        ".dylib",
        ".plist",
    }
)


def tika_version_is_current(version_text: str) -> bool:
    """Whether a Tika ``/version`` response is on the current stable line."""
    match = re.search(r"\d+(?:\.\d+)+", str(version_text or ""))
    return bool(match) and version_at_least(match.group(0), MIN_TIKA_VERSION)


__all__ = ["MIN_TIKA_VERSION", "TIKA_4_0_0_KNOWN_FORMATS", "tika_version_is_current"]
